platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

target 'Commissary Deli Kiosk' do
  # Pods for rn_oreo
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Commissary Deli KioskTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Commissary Deli Kiosk-tvOS' do
  # Pods for rn_oreo-tvOS

  target 'Commissary Deli Kiosk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
